(function(root){
    const messages = {
        "贡献本次研究": "Contribute this Run’s research",
        "社区 Wiki": "Community Wiki",
        "更新本地 Wiki": "Update local Wiki",
        "下载社区 Wiki 的最新内容，供之后新建的迁移实例使用。": "Download the latest community Wiki content for new migration instances.",
        "正在更新 Wiki…": "Updating Wiki…",
        "本地 Wiki 已更新，之后新建的迁移实例将使用最新内容。": "Local Wiki updated. New migration instances will use the latest content.",
        "研究贡献": "Research contributions",
        "GitHub CLI 优先使用系统凭据存储；不可用时可能在本机私有目录保存凭据。系统存储可能与其他 gh 安装共享。凭据不会加入贡献草稿。": "GitHub CLI prefers the system credential store. If unavailable, it may save credentials in a private local directory. System storage may be shared with other gh installations. Credentials are excluded from contribution drafts.",
        "关闭研究贡献": "Close research contributions",
        "审阅并编辑本地研究草稿，再向社区 Wiki 提交 Draft PR。维护者审阅后决定是否合并。": "Review and edit local research drafts, then submit a Draft PR to the community Wiki. Maintainers review contributions before merging.",
        "GitHub 账号": "GitHub account",
        "在浏览器中登录 GitHub": "Sign in to GitHub in browser",
        "打开 GitHub 登录页面，输入以下一次性代码并完成授权。": "Open the GitHub sign-in page, enter this one-time code, and authorize access.",
        "打开 GitHub 登录页面": "Open GitHub sign-in page",
        "取消登录": "Cancel sign-in",
        "本地草稿": "Local drafts",
        "暂无研究草稿。在迁移实例中导出研究结果后，可在这里审阅并提交。": "No research drafts yet. Export research from a migration instance to review and submit it here.",
        "贡献标题": "Contribution title",
        "研究内容": "Research content",
        "可修改研究结论和证据；请保留 JSON 格式。": "Edit research conclusions and evidence, keeping the JSON format.",
        "PR 说明": "PR description",
        "提交说明（可选）": "Submission description (optional)",
        "查看 Draft PR": "View Draft PR",
        "保存草稿": "Save draft",
        "提交 Draft PR": "Submit Draft PR",
        "已提交 Draft PR": "Draft PR submitted",
        "草稿": "Draft",
        "请安装 GitHub CLI（gh），然后重新打开此窗口。安装说明：cli.github.com。": "Install GitHub CLI (gh), then reopen this dialog. Installation instructions: cli.github.com.",
        "已登录：{0}": "Signed in as {0}",
        "提交前请在浏览器中登录 GitHub。": "Sign in to GitHub in your browser before submitting.",
        "等待浏览器授权…": "Waiting for browser authorization…",
        "Draft PR 将以 GitHub 账号 {0} 提交。": "The Draft PR will be submitted as GitHub account {0}.",
        "登录后可提交 Draft PR。": "Sign in to submit a Draft PR.",
        "有未保存的修改。关闭窗口后，修改会保留在本次应用会话中。": "Unsaved changes. Closing this dialog keeps your edits for this app session.",
        "草稿已保存到本机。": "Draft saved locally.",
        "正在保存…": "Saving…",
        "正在提交 Draft PR…": "Submitting Draft PR…",
        "正在启动登录…": "Starting sign-in…",
        "GitHub 登录失败，请重试。": "GitHub sign-in failed. Please try again.",
        "正在导出研究草稿…": "Exporting research drafts…",
        "正在读取研究草稿…": "Loading research drafts…",
        "Draft PR 已提交，等待维护者审阅。": "Draft PR submitted, awaiting maintainer review.",
        "所选备用模型已从连接中移除，请重新选择。": "The selected fallback model was removed from this connection. Please choose another model.",
        "备用设置模式无效。": "Fallback mode is invalid.",
        "备用连接标识无效。": "Fallback connection ID is invalid.",
        "备用连接标识已被使用。": "Fallback connection ID is already in use.",
        "备用连接名称不能为空，且不能超过 120 个字符。": "Fallback connection name is required and must be at most 120 characters.",
        "不支持此备用 API 协议。": "Fallback API type is unsupported.",
        "请填写有效的备用 HTTP(S) API 地址。": "Fallback API URL is required and must be a valid HTTP(S) URL.",
        "备用 API 地址须为 HTTP(S)，且不含凭据、查询参数或片段。": "Fallback API URL must be HTTP(S) without credentials, query, or fragment.",
        "备用 API 密钥格式无效。": "Fallback API key is invalid.",
        "备用连接的模型目录无效。": "Fallback provider has an invalid model catalog.",
        "API 连接数量已达到 16 个的上限。": "Fallback provider catalog has reached the 16-provider limit.",
        "此 API 的模型数量已达到 64 个的上限。": "Fallback provider has reached the 64-model limit.",
        "请填写备用模型的详细规格。": "Fallback model details are required.",
        "请填写备用模型名称。": "Fallback model name is required.",
        "备用模型名称格式无效。": "Fallback model name is invalid.",
        "备用模型上下文窗口必须为不大于 100000000 的正整数。": "Fallback context window must be a positive whole number at most 100000000.",
        "备用模型最大输出必须为正整数且不大于上下文窗口。": "Fallback maximum output must be positive and no greater than context window.",
        "备用模型支持的推理强度无效。": "Fallback model reasoning efforts are invalid.",
        "此备用模型不支持所选推理强度。": "Fallback reasoning effort is not supported by this model.",
        "备用模型规格与此 API 已有同名模型不一致。请重新选择或在高级配置中修改。": "Fallback model conflicts with an existing model on this API.",
        "所选备用连接的标识无效。": "Selected fallback provider ID is invalid.",
        "所选备用连接已不存在，请重新选择。": "Selected fallback provider was not found in settings.",
        "请填写备用 API 连接信息。": "Fallback provider details are required.",
        "模型设置中的角色或阶段配置无效。": "Model settings contain an invalid selection map.",
        "模型设置包含无效的模型选择。": "Model settings contain an invalid selection.",
        "API 连接列表格式无效。": "Provider settings must be a list.",

        "应用更新": "App updates",
        "检查更新": "Check for updates",
        "启动时自动检查 GitHub 正式版。发现新版后，可前往发布页手动下载。": "Checks GitHub stable releases at startup. Download new versions from the release page.",
        "前往发布页下载": "Open download page",
        "备用模型（可选）": "Fallback model (optional)",
        "备用模型设置": "Fallback settings",
        "已配置备用：{0}": "Configured fallback: {0}",
        "尚未配置备用模型。": "No fallback model configured.",
        "保持现有设置": "Keep existing settings",
        "统一设置备用模型": "Set a shared fallback model",
        "关闭所有备用模型": "Disable all fallback models",
        "明确的 API 认证、额度、限流或服务不可用错误可触发一次切换；普通超时或已执行工具的失败回合不会自动重放。": "Definitive API authentication, quota, rate limit or availability errors can trigger one switch. Ordinary timeouts and failed turns that already used tools are not replayed.",
        "应用到所有角色与阶段；与主模型及推理强度相同的项不再设置备用。": "Applies to all roles and stages. Selections already using this model and reasoning effort need no fallback.",
        "备用 API 连接": "Fallback API connection",
        "新增独立备用 API": "Add a separate fallback API",
        "选择已配置模型": "Choose a configured model",
        "备用推理强度": "Fallback reasoning effort",
        "沿用此连接的密钥与模型规格；可在高级配置中修改。": "Uses this connection’s saved key and model limits. Edit them in Advanced settings.",
        "尚未检查更新。": "Updates have not been checked yet.",
        "正在检查更新…": "Checking for updates…",
        "当前已是最新正式版。": "You are up to date with stable releases.",
        "暂时无法检查更新，请稍后重试。": "Could not check for updates. Please try again later.",
        "发现新版本 {0}": "New version available: {0}",
        "请在 ModPort 桌面窗口中检查更新。": "Check for updates in the ModPort desktop app.",
        "尚无可用的正式版发布，或暂时无法访问发布渠道。": "No stable release is available, or the release channel cannot be accessed.",
        "当前应用版本：{0}": "Current app version: {0}",
        "上次检查：{0}": "Last checked: {0}",

        "执行总览": "Execution overview",
        "返回 Supervisor 对话": "Back to Supervisor chat",
        "收起总览，返回对话": "Collapse overview to return to chat",
        "展开查看用量、工作区与任务": "Expand for usage, workspace, and tasks",

        "困难任务：{0} · {1}": "Difficult tasks: {0} · {1}",
        "常规 Coder：{0} · {1}": "Routine Coder: {0} · {1}",
        "模型配置步骤": "Model setup steps",
        "API 连接": "API connection",
        "困难任务模型": "Difficult-task model",
        "常规 Coder 模型": "Routine Coder model",
        "上一步": "Back",
        "下一步": "Next",
        "高级配置：连接目录与逐角色覆盖": "Advanced: connections and role overrides",
        "连接你的模型服务": "Connect your model service",
        "配置困难任务模型": "Configure the difficult-task model",
        "配置常规 Coder 模型": "Configure the routine Coder model",
        "先填写 API 地址和 Key。接下来分别配置困难任务与常规 Coder 使用的模型。": "Enter the API URL and key first. Next, configure a model for difficult tasks and a model for routine coding.",
        "用于迁移规划、复杂问题分析与需求审查。建议选择推理能力较强的模型。": "Used for migration planning, complex analysis, and requirements review. Choose a model with strong reasoning.",
        "用于日常代码编写与修复，也作为其余任务的默认模型。": "Used for everyday coding and fixes, and as the default for other tasks.",
        "模型名称": "Model name",
        "填写 API 服务提供的模型名称": "Enter the model name from your API service",
        "模型细节": "Model details",
        "请按模型服务提供的规格填写；不支持推理强度的模型使用 none。": "Enter the specifications supplied by your model service. Use none for models without reasoning effort support.",
        "分别配置两个模型": "Configure models separately",
        "使用与困难任务相同的模型": "Use the difficult-task model",
        "共用第一个 API 连接": "Share the first API connection",
        "使用独立 API 连接": "Use a second API connection",
        "两个用途将共用困难任务的连接、模型和推理强度。": "Both purposes will use the difficult-task connection, model, and reasoning effort.",
        "为常规 Coder 单独填写 API 地址和 Key。": "Enter a separate API URL and key for routine coding.",
        "常规 Coder 共用第一步的 API 地址和 Key。": "Routine coding uses the API URL and key from step 1.",
        "另有 {0} 项单独设置会保留，可在高级配置中检查。": "There are {0} explicit overrides that will be preserved. Review them in advanced settings.",
        "两个用途分别保存；需要时可展开高级配置调整具体角色。": "The two purposes are saved separately. Open advanced settings to adjust individual roles.",
        "困难任务：{0} · {1}\n常规 Coder：{2} · {3}": "Difficult tasks: {0} · {1}\nRoutine Coder: {2} · {3}",
        "尚未创建迁移实例": "No migration instance yet",
        "尚无执行数据": "No execution data yet",
        "可以先检查执行界面；配置完成并开始迁移后，这里会显示真实任务和进度。": "You can inspect this page now. Real tasks and progress will appear after you finish setup and start a migration.",
        "开始迁移后可对话": "Chat becomes available after launch",
        "Supervisor 对话将在实例启动后启用。": "Supervisor chat becomes available after the instance starts.",
        "启动前请补全项目名称、源码和版本信息。": "Before starting, complete the project name, source, and version information.",
        "第一组 API": "First API",
        "第二组 API": "Second API",
        "请输入有效的连接标识。": "Enter a valid connection ID.",
        "请输入连接名称。": "Enter a connection name.",
        "请输入 API 地址。": "Enter an API URL.",
        "请输入模型名称。": "Enter a model name.",
        "请输入有效的模型名称。": "Enter a valid model name.",
        "上下文窗口必须为不大于 100000000 的正整数。": "Context window must be a positive whole number at most 100000000.",
        "最大输出必须为正整数且不大于上下文窗口。": "Maximum output must be positive and no greater than the context window.",
        "请填写支持的推理强度。": "Enter supported reasoning efforts.",
        "所选推理强度不在该模型支持的范围内。": "The selected reasoning effort is not supported by this model.",
        "第二组 API 必须使用不同的连接标识。": "The second API must use a different connection ID.",
        "同一 API 中同名模型的规格必须一致。请使用相同模型按钮，或填写不同模型名称。": "Models with the same name on one API must have matching details. Use the same-model button or enter different model names.",

        "沿用代码编写模型": "Use the coding model",
        "语言": "Language",
        "简体中文": "简体中文",
        "English": "English",
        "未开始": "Not started",
        "排队中": "Queued",
        "运行中": "Running",
        "等待处理": "Waiting",
        "已完成": "Completed",
        "执行完成": "Execution complete",
        "失败": "Failed",
        "有失败项": "Has failed tasks",
        "{0} 项失败": "{0} failed",
        "任务 ID：{0}": "Task ID: {0}",
        "错误码：{0}": "Error code: {0}",
        "已取消": "Cancelled",
        "取消处理中": "Cancelling",
        "准备中": "Preparing",
        "未知": "Unknown",
        "编写与执行": "Build and run",
        "审查与监督": "Review and supervision",
        "跳到主要内容": "Skip to main content",
        "ModPort 项目首页": "ModPort home",
        "迁移步骤": "Migration steps",
        "项目": "Project",
        "设置": "Settings",
        "执行": "Run",
        "配置模型": "Configure models",
        "正在连接": "Connecting…",
        "NEW MIGRATION / 新建迁移": "NEW MIGRATION",
        "从项目开始。": "Start with a project.",
        "选择源代码，确认版本，再交给 ModPort。": "Choose your source, confirm the versions, then let ModPort take it from there.",
        "项目与仓库": "Project and repository",
        "项目名称": "Project name",
        "你的 Mod 项目": "Your mod project",
        "用于识别本次迁移实例。": "Used to identify this migration instance.",
        "代码来源": "Source",
        "远程仓库": "Remote repository",
        "本地代码库": "Local source",
        "本地源码文件夹": "Local source folder",
        "选择包含 Mod 源码的文件夹": "Choose a folder containing mod source code",
        "选择文件夹": "Choose folder",
        "选择运行目录策略：Git 项目可新建分支和独立工作树；也可复制源码，或明确选择直接修改原目录。": "Choose where to work: create a branch and worktree for a Git project, copy the source, or modify the original folder directly.",
        "源码仍会发送给所配置的模型 API；需要离线使用时，请配置本机模型服务。": "Source code is still sent to the configured model API. For offline use, configure a local model service.",
        "GitHub / Gitee 仓库地址": "GitHub / Gitee repository URL",
        "识别仓库": "Detect repository",
        "读取分支、标签与版本信息后，仍可手动确认和修改。": "Branches, tags, and version details will be detected; you can still review and edit them.",
        "分支 / 标签": "Branch / tag",
        "默认分支": "Default branch",
        "源版本": "Source version",
        "加载器": "Loader",
        "加载器版本": "Loader version",
        "例如 1.20.1": "e.g. 1.20.1",
        "自动识别或手动填写": "Detected automatically or enter manually",
        "目标版本": "Target version",
        "例如 1.21.1": "e.g. 1.21.1",
        "确认目标加载器版本": "Confirm the target loader version",
        "版本信息将在启动时固定。": "Version details are fixed when the run starts.",
        "确认项目，继续": "Confirm project and continue",
        "最近的实例": "Recent instances",
        "正在读取本机实例…": "Loading local instances…",
        "刷新实例列表": "Refresh instance list",
        "每次迁移独立保存。关闭窗口后，可从最近的实例重新打开。": "Each migration is saved separately. Reopen it from Recent instances after closing this window.",
        "源项目功能以确认结果和源码阅读为依据；目标行为由实际测试验证。": "Source behavior is based on user confirmation and source reading; target behavior is checked by running tests.",
        "EXECUTION SETTINGS / 执行设置": "EXECUTION SETTINGS",
        "设定这次迁移。": "Set up this migration.",
        "本地工作区": "Local workspace",
        "运行期间如何处理所选源码": "How to handle the selected source during the run",
        "Git 新分支与独立工作树": "New Git branch and worktree",
        "在所选 Git 仓库中创建你命名的分支，并在独立工作树里迁移。": "Create a branch with your chosen name in the selected Git repository and migrate in a separate worktree.",
        "新分支名称": "New branch name",
        "请输入分支名称；ModPort 不会替你生成名称。": "Enter a branch name. ModPort will not generate one for you.",
        "复制源码": "Copy source",
        "把当前文件和未提交修改复制到独立目录中。": "Copy the current files and uncommitted changes into a separate folder.",
        "直接修改所选目录": "Modify the selected folder directly",
        "迁移过程中的文件改动会写入原目录。": "Migration changes will be written to the original folder.",
        "直接修改所选目录，不新建分支、不复制备份；运行期间请勿同时编辑": "The selected folder will be modified directly, with no new branch or backup. Do not edit it during the run.",
        "我已了解，并会在运行期间停止同时编辑此目录。": "I understand and will stop editing this folder while the run is in progress.",
        "执行预算": "Run budget",
        "总时间限制": "Total time limit",
        "小时": "hours",
        "所有任务共享本次执行的总时间。": "All tasks share this run's total time limit.",
        "总 Token 限制": "Total token limit",
        "模型用量由运行服务记录。": "Model usage is recorded by the run service.",
        "模型与推理强度独立配置。本次选择会随实例保存。": "Models and reasoning effort are configured separately. These choices are saved with the instance.",
        "模型配置": "Model settings",
        "API 连接、上下文与任务模型使用已保存的配置。可在启动前调整。": "API connections, context limits, and task models use saved settings. You can adjust them before starting.",
        "← 返回项目": "← Back to project",
        "启动前请确认项目版本与执行预算。": "Confirm the project versions and run budget before starting.",
        "开始迁移": "Start migration",
        "MIGRATION INSTANCE / 迁移实例": "MIGRATION INSTANCE",
        "正在读取实例…": "Loading instance…",
        "正在读取对话…": "Loading conversation…",
        "读取中": "Loading",
        "刷新": "Refresh",
        "新建项目": "New project",
        "取消执行": "Cancel run",
        "执行用量": "Run usage",
        "已用时间": "Time used",
        "已用 TOKEN": "Tokens used",
        "服务状态": "Service status",
        "正在读取": "Loading",
        "WORKSPACE / 工作区": "WORKSPACE",
        "打开工作区": "Open workspace",
        "迁移任务": "Migration tasks",
        "运行监督与对话": "Run supervision and chat",
        "Supervisor 对话": "Supervisor conversation",
        "对话记录会在这里显示。": "Conversation history will appear here.",
        "向 Supervisor 提问或补充说明": "Ask the Supervisor a question or add context",
        "询问当前进展，或补充迁移要求…": "Ask about progress or add migration requirements…",
        "Ctrl / ⌘ + Enter 发送": "Ctrl / ⌘ + Enter to send",
        "发送": "Send",
        "对话不会直接取消执行；生命周期操作请使用上方控制。": "Chat does not cancel a run. Use the controls above for run actions.",
        "等待连接服务": "Waiting for service connection",
        "MODEL SETTINGS / 模型配置": "MODEL SETTINGS",
        "先连接，再选择模型。": "Connect first, then choose models.",
        "关闭模型配置": "Close model settings",
        "保存到本机，供后续项目使用。正在执行的实例保留启动时的配置。": "Saved locally for future projects. Active instances keep the settings they started with.",
        "API 连接与可用模型": "API connections and available models",
        "＋ 添加连接": "＋ Add connection",
        "任务使用的模型": "Models used by tasks",
        "可按组或逐角色设置": "Set by group or by role",
        "大组设置仅在修改后应用。展开可单独配置角色；已有阶段覆盖和回退配置会保留。": "Group settings apply only when changed. Expand to configure roles individually; existing stage overrides and fallback settings are preserved.",
        "密钥留空保留已存密钥。保存配置不会发起模型请求。": "Leave a key blank to keep the saved key. Saving settings does not send a model request.",
        "取消": "Cancel",
        "保存配置": "Save settings",
        "运行环境": "Runtime environment",
        "关闭运行环境": "Close runtime environment",
        "选择需要执行的准备操作。检查结果由本机服务提供。": "Choose which setup actions to run. Check results are provided by the local service.",
        "重新检查": "Check again",
        "关闭": "Close",
        "取消本次执行？": "Cancel this run?",
        "将请求停止当前实例。任务清理可能需要时间，最终状态以服务返回为准。": "This will request that the current instance stop. Task cleanup may take time; the service will report the final status.",
        "继续执行": "Keep running",
        "确认取消": "Confirm cancellation",
        "服务返回了无法读取的响应 ({0})": "The service returned an unreadable response ({0})",
        "请求失败 ({0})": "Request failed ({0})",
        "本机服务没有返回有效数据。": "The local service returned invalid data.",
        "环境就绪": "Environment ready",
        "环境需要准备": "Environment setup required",
        "服务未提供详细检查结果。": "The service did not provide details for this check.",
        "准备此项": "Set up",
        "正在准备…": "Setting up…",
        "操作已完成。请查看最新环境检查。": "Action complete. Check the latest environment status.",
        "服务尚未提供环境检查结果。": "The service has not provided environment check results.",
        "请打开运行环境，完成准备后再启动。": "Open Runtime environment and complete setup before starting.",
        "正在打开…": "Opening…",
        "还没有迁移实例。创建项目后会显示在这里。": "There are no migration instances yet. New projects will appear here.",
        "多个设置 · 保持现有选择": "Multiple settings · keep current selections",
        "填写模型设置": "Enter model settings",
        "模型": "Model",
        "推理强度": "Reasoning effort",
        "修改后应用于本组所有角色；也可以展开逐项调整。": "Changes apply to every role in this group. Expand to adjust roles individually.",
        "单独配置角色与阶段 · {0} 项": "Configure roles and stages individually · {0} items",
        "默认模型：{0} · {1}": "Default model: {0} · {1}",
        "尚未读取模型配置": "Model settings have not been loaded",
        "添加一个 API 连接，再填写服务提供的模型名称与上下文上限。": "Add an API connection, then enter the model names and context limits provided by the service.",
        "连接 {0}": "Connection {0}",
        "移除连接": "Remove connection",
        "连接名称": "Connection name",
        "连接标识": "Connection ID",
        "API 协议": "API protocol",
        "OpenAI 兼容 · Chat Completions": "OpenAI-compatible · Chat Completions",
        "API 地址": "API URL",
        "API 密钥": "API key",
        "已配置 · 留空保留": "Configured · leave blank to keep",
        "输入 API 密钥；本地免密服务可留空": "Enter an API key; leave blank for a local service that needs no key",
        "模型 {0}": "Model {0}",
        "模型 ID": "Model ID",
        "服务提供的模型名称": "Model name provided by the service",
        "上下文窗口 · Tokens": "Context window · tokens",
        "最大输出 · Tokens": "Maximum output · tokens",
        "支持的推理强度": "Supported reasoning efforts",
        "例如 low, medium, high；不支持可留空": "e.g. low, medium, high; leave blank if unsupported",
        "用于所有任务": "Use for all tasks",
        "所有任务已选择 {0}；保存后生效。": "{0} is now selected for all tasks. Save to apply.",
        "移除模型": "Remove model",
        "＋ 添加模型": "＋ Add model",
        "读取配置…": "Loading settings…",
        "仓库信息已读取。请确认分支和源版本，并填写目标版本。": "Repository details loaded. Confirm the branch and source version, then enter the target version.",
        "仓库识别完成。版本信息可以继续编辑。": "Repository detected. You can still edit the version details.",
        "复制所选源码": "Copy selected source",
        "未检测到可用的 Git。": "No usable Git installation was found.",
        "所选目录不是 Git 仓库。": "The selected folder is not a Git repository.",
        "当前分支：{0}": "Current branch: {0}",
        "当前分支：未检出": "Current branch: detached",
        "工作区有未提交修改": "Working tree has uncommitted changes",
        "工作区干净": "Working tree is clean",
        "已有提交": "Contains commits",
        "尚无提交": "No commits yet",
        "无法使用 Git 分支工作树：{0} 仍可复制源码，或选择直接修改原目录。": "Git branch worktree is unavailable: {0} You can still copy the source or modify the original folder directly.",
        "Git 分支工作树不可用：{0} 可选择复制源码，或确认后直接修改原目录。": "Git branch worktree is unavailable: {0} You can copy the source or confirm that you want to modify the original folder directly.",
        "仓库还没有提交，无法创建新分支。": "The repository has no commits, so a new branch cannot be created.",
        "当前仓库不满足创建新分支的条件。": "The repository does not meet the requirements for creating a new branch.",
        "本次策略：{0}{1}": "Workspace strategy: {0}{1}",
        " · 分支 {0}": " · branch {0}",
        "请输入新分支名称。": "Enter a new branch name.",
        "分支名称格式无效。请移除空格及 Git 禁止的符号，并确认各段不以点号开头。": "Invalid branch name. Remove spaces and characters Git does not allow, and make sure no path segment starts with a period.",
        "直接修改原目录需要先确认上方提示。": "Confirm the notice above before modifying the original folder directly.",
        "请在 ModPort 桌面窗口中选择本地文件夹。": "Choose a local folder in the ModPort desktop window.",
        "本机服务没有返回有效的源码选择凭据。": "The local service did not return valid source-selection credentials.",
        "未能可靠识别 Minecraft 版本，请手动填写。": "Could not reliably detect the Minecraft version. Enter it manually.",
        "已选择本地代码库。请确认源版本和本地工作区策略。": "Local source selected. Confirm the source version and workspace strategy.",
        "准备": "Preparation",
        "实施": "Implementation",
        "测试": "Testing",
        "服务尚未提供此组任务。": "The service has not provided tasks for this group.",
        "展开另外 {0} 个进行中的任务": "Show {0} more active tasks",
        "已完成 {0} 项 · 展开查看": "{0} completed · expand to view",
        "阶段已结束。服务未提供展开项。": "This stage has ended. The service provided no expandable tasks.",
        "等待任务开始。未开始的任务会暂时隐藏。": "Waiting for tasks to start. Not-started tasks are temporarily hidden.",
        "YOU / 你": "YOU",
        "还没有对话。可以询问进展，或补充说明。": "No messages yet. Ask about progress or add context.",
        "工作区": "Workspace",
        "实例目录：{0}": "Instance folder: {0}",
        "所选源码：{0}": "Selected source: {0}",
        "分支 {0}": "Branch {0}",
        " · 已知用量，统计未完整": " · known usage; totals are incomplete",
        " · 用量统计未完整": " · usage totals are incomplete",
        "已同步": "Synced",
        "更新于 {0}": "Updated at {0}",
        "实例已结束": "Instance ended",
        "正在处理对话": "Handling your message",
        "可发送消息": "Ready for a message",
        "连接中断 · 显示上次状态": "Connection interrupted · showing last known status",
        "无法更新实例：{0}。可点击刷新重试。": "Could not refresh the instance: {0}. Click Refresh to try again.",
        "无法连接 ModPort：{0}。运行环境和实例列表中可重试。": "Could not connect to ModPort: {0}. Retry from Runtime environment or Recent instances.",
        "读取仓库…": "Reading repository…",
        "读取中…": "Loading…",
        "读取本地源码…": "Reading local source…",
        "请先选择本地源码文件夹。": "Choose a local source folder first.",
        "请先确认项目，并完成运行环境准备。": "Confirm the project and complete runtime setup first.",
        "正在启动…": "Starting…",
        "请输入有效的总时间和 Token 限制。": "Enter valid total time and token limits.",
        "服务未返回实例编号。": "The service did not return an instance ID.",
        "发送中…": "Sending…",
        "消息已接收，由 Supervisor 处理。": "Message received. The Supervisor will handle it.",
        "正在请求…": "Submitting request…",
        "已提交取消请求。正在等待服务返回任务与清理状态。": "Cancellation requested. Waiting for the service to report task and cleanup status.",
        "正在保存…": "Saving…",
        "模型配置已保存，新实例将使用这些设置。": "Model settings saved. New instances will use these settings.",
        "配置保存失败，请重试。": "Could not save settings. Try again.",
        "检查中…": "Checking…",
        "只能在 ModPort 桌面窗口中打开实例工作区。": "Open an instance workspace from the ModPort desktop window.",
        "已在文件管理器中打开此实例工作区。": "Opened this instance's workspace in the file manager.",
        "服务连接失败": "Service connection failed",
        "无法读取本机实例。请检查服务并点击刷新。": "Could not load local instances. Check the service and click Refresh.",
        "OpenAI Responses": "OpenAI Responses",
        "LOCAL WORKSPACE": "LOCAL WORKSPACE"
    };
    if(typeof module==='object' && module.exports) module.exports=messages;
    else root.ModPortEnglish=messages;
})(globalThis);
