'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({});
vm.runInContext(fs.readFileSync('src/modport/web_static/graph.js', 'utf8'), context);
const layout = steps => context.layoutWorkflow(steps);
const task = (id, dependencies = [], scheduled = true) => ({id, dependencies, scheduled});
const graph = layout([task('join',['left','right']), task('left',['root']), task('root'), task('right',['root']), task('future',[],false)]);
assert.deepEqual(Array.from(graph.layers, row => Array.from(row, s=>s.id)), [['root'], ['left','right'], ['join']]);
assert.equal(graph.edges.length, 4);
assert.equal(graph.nodes.get('left').y, graph.nodes.get('right').y);
assert.notEqual(graph.nodes.get('left').x, graph.nodes.get('right').x);
assert.equal(graph.upcoming.length,1);
assert.equal(graph.nodes.has('future'),false);
const broken = layout([task('a',['b']),task('b',['a']),task('missing',['outside']),task('child',['missing']),task('ok')]);
assert.equal(broken.nodes.size,1);
assert.equal(broken.unresolved.length,4);
assert.equal(broken.edges.length,0);
assert.equal(layout([]).nodes.size,0);
const inherited = layout([{...task('prior'), inherited:true},task('fresh'),task('next',['prior'])]);
assert.equal(inherited.nodes.has('prior'),false);
assert.equal(inherited.layers[0].length,2);
assert.equal(inherited.edges.length,0);
assert.equal(inherited.inherited.length,1);
assert.equal(inherited.unresolved.length,0);
const manyPrior = layout([...Array.from({length:14},(_,i)=>({...task('prior'+i),inherited:true})),task('current')]);
assert.equal(manyPrior.nodes.size,1);
assert.equal(manyPrior.width,320);
assert.equal(manyPrior.inherited.length,14);
console.log('PASS: fork/join, parallel layout, placeholders, missing refs, cycles and inherited boundaries');
