"""Bind a verified Maven seed to a Run and expose it read-only to Gradle."""
from pathlib import Path
import json

from .evidence import file_digest, verified_path


REPOSITORY = "artifacts/dependency-repository"
INIT_SCRIPT = "artifacts/dependency-repository.init.gradle"


def repository_init_script(coordinates):
    """Route only exact seeded versions locally, including buildscript lookups."""
    # Coordinates were validated by the repository reader. JSON strings still
    # need single-quote Groovy literals to avoid dollar-string interpolation.
    filters = []
    for coordinate in sorted(coordinates):
        group, artifact, version = coordinate.split(":")
        if any(any(c not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.-" for c in v)
               for v in (group, artifact, version)):
            raise ValueError("unsafe dependency coordinate for Gradle init script")
        filters.append(f"                includeVersion('{group}', '{artifact}', '{version}')")
    if not filters:
        return "// ModPort: no verified Maven seeds in this Run.\n"
    return """// Generated by ModPort from the frozen dependency manifest.
def configureSeed = { repos ->
    if (repos.findByName('ModPortVerifiedSeed') == null) {
        repos.exclusiveContent {
            forRepository {
                repos.maven {
                    name = 'ModPortVerifiedSeed'
                    url = 'file:/modport-dependencies/repository'
                    metadataSources { mavenPom(); artifact() }
                }
            }
            filter {
""" + "\n".join(filters) + """
            }
        }
    }
}
def useProjectRepositories = true
gradle.settingsEvaluated { settings ->
    configureSeed(settings.dependencyResolutionManagement.repositories)
    useProjectRepositories = settings.dependencyResolutionManagement.repositoriesMode.get().name() == 'PREFER_PROJECT'
}
gradle.beforeProject { project ->
    if (useProjectRepositories) { configureSeed(project.repositories) }
    configureSeed(project.buildscript.repositories)
}
"""


def prepare_dependency_seed(store, root):
    """Freeze a copy and its init script as submission evidence."""
    from .dependency_cache import snapshot_repository
    root = Path(root)
    store = Path(store).absolute()
    if store == root or store.is_relative_to(root) or root.is_relative_to(store):
        raise ValueError("shared dependency store and Run must not contain each other")
    manifest = snapshot_repository(store, root / REPOSITORY)
    script = root / INIT_SCRIPT
    script.write_text(repository_init_script(manifest["artifacts"]), encoding="utf-8")
    return {
        alias: {"path": relative, "sha256": file_digest(root / relative), "media_type": media}
        for alias, relative, media in (
            ("dependency_repository", REPOSITORY + "/manifest.json", "application/json"),
            ("dependency_repository_init", INIT_SCRIPT, "text/plain"),
        )
    }


def dependency_mounts(root, args):
    """Authenticate the frozen seed and add a read-only mount and init flag.

    Shared storage is never exposed to a build. Later shared publications
    cannot change this Run's input, and no writable Gradle cache is promoted.
    """
    from .dependency_cache import verify_repository
    root = Path(root)
    header_path = root / "run.json"
    if not header_path.exists():
        return [], list(args)
    if header_path.is_symlink():
        raise RuntimeError("unsafe dependency seed Run header")
    header = json.loads(header_path.read_text(encoding="utf-8"))
    refs = header.get("initial_refs", {})
    ref = refs.get("dependency_repository")
    if ref is None:
        if header.get("request", {}).get("dependency_cache"):
            raise RuntimeError("configured dependency repository is not frozen")
        return [], list(args)
    try:
        if ref["path"] != REPOSITORY + "/manifest.json":
            raise ValueError("unexpected dependency repository path")
        manifest_path = verified_path(root, ref)
        if file_digest(manifest_path) != ref.get("sha256"):
            raise ValueError("dependency manifest differs from its frozen digest")
        script_ref = refs["dependency_repository_init"]
        if script_ref["path"] != INIT_SCRIPT:
            raise ValueError("unexpected dependency init script path")
        script = verified_path(root, script_ref)
        if file_digest(script) != script_ref.get("sha256"):
            raise ValueError("dependency init script differs from its frozen digest")
        manifest = verify_repository(root / REPOSITORY)
    except (OSError, ValueError, KeyError) as error:
        raise RuntimeError(f"dependency seed validation failed: {error}") from error
    result = list(args)
    if not manifest["artifacts"]:
        return [], result
    # Client harness launch arguments wrap gradlew; insert at the wrapper
    # itself rather than sending Gradle flags to the Python launcher.
    if "/workspace/gradlew" not in result:
        return [], result
    offset = result.index("/workspace/gradlew") + 1
    result[offset:offset] = ["--init-script", "/modport-dependency.init.gradle"]
    mounts = ["--ro-bind", str(root / REPOSITORY), "/modport-dependencies",
              "--ro-bind", str(script), "/modport-dependency.init.gradle"]
    return mounts, result


def gradle_failure_kind(output):
    """Classify dependency transport failures without restarting the build."""
    lower = output.lower()
    if ("received status code 429" in lower or "429 too many requests" in lower):
        return "dependency_rate_limited"
    if any(marker in lower for marker in (
        "unknownhostexception", "temporary failure in name resolution",
        "received status code 503", "connect timed out", "connection timed out",
        "read timed out", "connection refused", "network is unreachable",
    )):
        return "dependency_resolution_failed"
    return "gradle_failed"
